var eligibleGames = [
"428: Shibuya Scramble",
"7 Billion Humans",
"A Way Out",
"Accounting+",
"Aegis Defenders",
"Alphabear 2",
"Alto's Odyssey",
"Among The Stars",
"Arca's Path VR",
"Artifact",
"Ashen",
"Assassin's Creed Odyssey",
"Assault Spy",
"Astro Bot: Rescue Mission",
"Atelier Lydie & Suelle: The Alchemists and the Mysterious Paintings",
"AXE.IO",
"Barbearian",
"Battle Princess Madelyn",
"Battlefield V",
"Beat Saber",
"Below",
"Blade Strangers",
"BlazBlue: Cross Tag Battle",
"Bloodstained: Curse of the Moon",
"Bravo Team",
"Brew Town",
"Bring You Home",
"Budget Cuts",
"Call of Duty: Black Ops IIII",
"Candles 'n Curses",
"Celeste",
"Chasm",
"CHUCHEL",
"Creed: Rise to Glory",
"CrossCode",
"Cube Escape: Paradox",
"Dandara",
"Dark Eclipse",
"Darksiders III",
"Dead Cells",
"Dead in Vinland",
"Death Mark",
"Defector",
"Deltarune Chapter 1",
"Deracine",
"Destiny 2: Forsaken",
"Detroit: Become Human",
"Dig Dog: Treasure Hunter",
"Dissembler",
"DJMAX Respect",
"Donut County",
"Dragalia Lost",
"Dragon Quest XI: Echoes of an Elusive Age",
"Dragonball FighterZ",
"EA Sports UFC 3",
"Echoes III",
"ELOH",
"Eternal",
"Evergarden",
"Evoland 2",
"Exapunks",
"F1 2018",
"Fallout 76",
"Far Cry 5",
"FAR: Lone Sailts",
"Fe",
"FIFA 19",
"Fighting EX Layer",
"Final Fantasy XV Pocket Edition",
"Firewall: Zero Hour",
"Flat Heroes",
"Flipping Death",
"Florence",
"Football Manager 2019",
"Forgotton Anne",
"Fortnite: Battle Royale",
"Forza Horizon 4",
"Frostpunk",
"Frozen Synapse 2",
"Full Metal Furies",
"God of War",
"Grimvalor",
"GRIS",
"Guacamelee! 2",
"Gun Club VR",
"Guns Gore and Canoli 2",
"Higurashi When They Cry Hou - Ch.6 Tsumihoroboshi",
"Hitman 2",
"holedown",
"Iconoclasts",
"Into The Breach",
"It's Full of Sparks",
"Just Dance 2019",
"Just Shapes and Beats",
"Kingdom Come: Deliverance",
"Kirby Battle Royale",
"Kirby Star Allies",
"La Mulana 2",
"Laser League",
"Layers of Fear: Legacy",
"Legend of Solgard",
"Life is Strange 2: Episode 1",
"Magic The Gathering Arena",
"Mario + Rabbids: Kingdom Battle – Donkey Kong Adventure",
"Mario Tennis Aces",
"Marvel's Spiderman",
"Megaman 11",
"Meterorfall: Journey",
"Minesweeper Genius",
"Minit",
"MLB The Show 18",
"Monster Boy and the Cursed Kingdom",
"Monster Hunter World",
"Moonlighter",
"Moss",
"Mothergunship",
"Motorsport Manager Mobile 3",
"Nantucket",
"NBA 2K19",
"NHL 19",
"Ni No Kuni II: Revenant Kingdom",
"Nintendo Labo",
"Octahedron",
"Octopath Traveler",
"Oddmar",
"One Hour One Life",
"Onrush",
"Overcooked! 2",
"Part Time UFO",
"Persona 3: Dancing Moon Night",
"Persona 5: Dancing In Starlight",
"PES 2019",
"Pig Eat Ball",
"Pillars of Eternity II: Deadfire",
"Pit People",
"PlayerUnknown's Battlegrounds Mobile",
"Pocket City",
"Pocket Run Pool",
"Pokemon: Let's Go, Pikachu! and Let's Go, Eevee!",
"Prey: Mooncrash",
"Project Warlock",
"Qube 2",
"Radiant Historia: Perfect Chronology",
"Radiant One",
"Railway Empire",
"Red Dead Redemption 2",
"Reed ^_^",
"Reigns: Game of Thrones",
"Return of the Obra Dinn",
"Rimworld",
"Rogue Aces",
"Rush",
"Sairento VR",
"Sea of Thieves",
"Semblance",
"Shadow of the Tomb Raider",
"Shadowgun Legends",
"Shapeshifting Detective",
"Shin Megami Tensei Liberation DX2",
"Sid Meier’s Civilization VI: Rise and Fall",
"Sneak Ops",
"SNK Heroines: Tag Team Frenzy",
"SoulCalibur VI",
"Splatoon 2: Octo Expansion",
"Sprint Vector",
"State of Decay 2",
"Subnautica",
"Super Hydorah",
"Super Mario Party",
"Super Mega Baseball 2",
"Super One More Jump",
"Super Smash Bros. Ultimate",
"Supertype",
"Surviving Mars",
"Sushi Striker: The Way of Sushido",
"Suzy Cube",
"Synthetik: Legion Rising",
"Teen Titans GO Figure!",
"Tetris Effect",
"The 25th Ward: The Silver Case",
"The Adventure Pals",
"The Awesome Adventures of Captain Spirit",
"The Banner Saga 3",
"The Council",
"The Crew 2",
"The Elder Scrolls Online: Summerset",
"The Forest",
"The Gardens Between",
"The House in Fata Morgana: A Requiem for Innocence",
"The Inpatient",
"The Messenger",
"The Missing: JJ Macfield and the Island of Memories",
"The Persistence",
"The Red Strings Club",
"The Room: Old Sins",
"The Sims 4 Seasons",
"The Vagrant",
"Thronebreaker: The Witcher Tale",
"Timespinner",
"Tiny Bubbles",
"Total War: WARHAMMER II Rise of the Tomb Kings",
"Touhou Luna Nights",
"Transference",
"Twinfold",
"Two Point Hospital",
"Unavowed",
"Under Night in-Birth Exe:Late[st]",
"Unforeseen Incidents",
"Unravel Two",
"Valkyria Chronicles 4",
"Valleys Between",
"Wandersong",
"Warhammer: Vermintide 2",
"WarioWare Gold",
"Where Shadows Slumber",
"World of Warships Blitz",
"Wreckfest",
"Xenoblade Chronicles 2 Torna The Golden Country",
"Yakuza 6: The Song of Life",
"Yakuza Kiwami 2",
"Yoku’s Island Express",
"ZeroRanger",
]

var eligibleRemasters = [
"Burnout Paradise Remastered",
"Dark Souls Remastered",
"Diablo III: The Eternal Collection",
"Divinity: Original Sin II - Defininitive Edition",
"Final Fantasy XII: The Zodiac Age",
"Final Fantasy XV: Windows Edition",
"Go Vacation",
"Katamari Damacy Reroll",
"Labyrinth of Refrain: Coven of Dusk",
"Luigi's Mansion",
"Lumines Remastered",
"Megadimension Neptunia VIIR",
"Pac-Man Championship Edition 2 Plus",
"Sega Genesis Classics",
"Shadow of the Colossus",
"Shantae: Half Genie Hero Ultimate Edition",
"Shenmue I & II",
"Shin Megami Tensei: Strange Journey Redux",
"Sid Meier's Civilization VI",
"SNK 40th Anniversary Collection",
"Spyro Reignited Trilogy",
"Street Fighter 30th Anniversary Collection",
"Sunset Overdrive",
"The World Ends With You: Final Remix",
"Valkyria Chronicles",
"Warframe",
"Zwei: The Arges Adventure",
]

export { eligibleGames, eligibleRemasters };